<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.2 setup script
 * Date: Sat, 01 Jul 2017 10:28:22 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'root';
$cfg['Servers'][$i]['hide_db'] = 'information_schema|performance_schema|mysql|sys';
/* End of servers configuration */

$cfg['blowfish_secret'] = '4TS_]x=\'yu5N.C>\\d{5\'W,;#z~\\ZtVuE';
$cfg['DefaultLang'] = 'fr';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>